applications:
    agentic-backend:
        configuration:
            ai:
                default_chat_model:
                    settings:
                        default_headers:
                            Authorization: ENC[AES256_GCM,data:kEvwnXIjLyWlY3VeVivoFckQuf8bnbqYiRmxF/KP7vy+eI7j0dV+,iv:OElh9Iv9zmCLjOhSw9i4vjuD+ksew87qX7RGbRsLuIg=,tag:j8y4QtCUJGt3UnbATuIViQ==,type:str]
        dotenv:
            OPENSEARCH_PASSWORD: ENC[AES256_GCM,data:byMSpACJZRJ/Tt7XLFmTHnv6Jw==,iv:FT9vaUQaAD47NUafSrT/ZpNeGhci7DmB9gU58F9d1u8=,tag:Ih32q+RR8uuDVnNsTLBPBg==,type:str]
            #ENC[AES256_GCM,data:PujQpdho7PnL23OOqQIBUXpRgJXljiOLI/YOuHx5Zzmg/7f6nFg6NYqpRk4=,iv:DpWA9E4CxpINOxd87KoTx3kqAjIcCJ5eLVdhncgUBmY=,tag:pCPapdNvJMaXzXkmy/lelg==,type:comment]
            OPENAI_API_KEY: ENC[AES256_GCM,data:CrpMShZ9g9OKZ5NfziRtAikdmAIVSr83Ik4WlFUwHgg=,iv:Vu0h3xAv+qMnlg7Bxg/P4IR2p8CIi16/vmXODKfGsTU=,tag:go9LQJ4HH+MlqOcju0cCsg==,type:str]
            KEYCLOAK_AGENTIC_CLIENT_SECRET: ENC[AES256_GCM,data:hmwbnBiwYTTMW68OP42F8IM0uFJH8ud1Fkgk5OIlrFo=,iv:Ds2F6ltCedeUOwfdhdSMZlc2tQTZpWshRcXWCGdLx7U=,tag:v5d9oNySBsMPIMcDiifdlQ==,type:str]
            M2M_CLIENT_SECRET: ENC[AES256_GCM,data:L99D23jUXnjakREqlovam4bGGXumZwkTMWv5j8TAcQo=,iv:IC0U1aQiaVgTP5y6xR+Z4oE/05haXRxiWnI8bfG20vk=,tag:WCXlvLcKxL+m/G84UVIazQ==,type:str]
            OPENFGA_API_TOKEN: ENC[AES256_GCM,data:psZ8tv3O5CQX0MFHGTy4EZXEPHo=,iv:lCWqUxGMXLQ5hhCfMpj0UNbBr3nU3XDSHvZREjQeRdw=,tag:V3WCAEbPYj4xaDWYN1xTAw==,type:str]
    knowledge-flow-backend:
        configuration:
            chat_model:
                settings:
                    default_headers:
                        Authorization: ENC[AES256_GCM,data:C+Vu4lTcQZ7VuKW4UFxsCGceAfdWKTK8+ypT2iArpfy4X/HwuotZ,iv:XAf3001DD+PlSa/OcN0JGaev4LExvdfcFs7Eg51usSk=,tag:+CCSNolomFf9VRBqi4m+Qw==,type:str]
            embedding_model:
                settings:
                    default_headers:
                        Authorization: ENC[AES256_GCM,data:NCfhZQcbBCid0rR3vdCKLCQAiD+vA/8ADm2CmN40bRRxD0LJqbv0,iv:i7GfduuXtwkPHOL2eqr4b9pXc+243Omz71jan3EeNIk=,tag:f6rAizf4dj7MIsJixkrzrw==,type:str]
        dotenv:
            OPENSEARCH_PASSWORD: ENC[AES256_GCM,data:IZG6aPzxyVRXUcdh5xLNeyRXsg==,iv:YQtdH4fppStkf6YdqF9qNdY92BPtAb5zD0U3YzPlS6A=,tag:X4ksVlxRiCM5rdnXvLe7tA==,type:str]
            #ENC[AES256_GCM,data:Mz5sMGXpei+ucDuX+gfZD54vNPPNtkXKR6RQNE2gwDnRjGs0/T7mDN0XEfw=,iv:43l4o8EKhIsCEICVSotg50N35eJ9NxXfrfcENEdAbYA=,tag:X8umuhsbWv6U8Mhc956HuQ==,type:comment]
            OPENAI_API_KEY: ENC[AES256_GCM,data:54aDHCUsC4ZuPNYs+Hd2B7Re9BY4xB1RDeCVh3/dTxk=,iv:CvyUGwDY10F94wZov1i5U5E7RNz46WgnPvUahZ2RkL0=,tag:j2z9x63lOti8YebrW4SI5w==,type:str]
            KEYCLOAK_KNOWLEDGE_FLOW_CLIENT_SECRET: ENC[AES256_GCM,data:p0B8hCB0PcucbiSQKOKpFIrfn1EsORTy9vQNchK9Rew=,iv:2OsM5/WSSkXv6lWrndR49vudR0tHxnudwoHdjzgdYuA=,tag:B0l/ekMsTHpGeqfGwZpDaA==,type:str]
            MINIO_SECRET_KEY: ENC[AES256_GCM,data:jX2yCg0U1Vck8NqeQyjUWE8Fhzs=,iv:7vyWnLTZT1kHVjXdWjnIosNZb15LiIrMVwv/iuERyu4=,tag:82jfCKD+6cLaPjLF7MpVtg==,type:str]
            OPENFGA_API_TOKEN: ENC[AES256_GCM,data:n+x4jWKrYnBd0x9ieNSFpVwO9Ag=,iv:rQc9BVb2Hxrn+sDwfrzwmziiRbV0VbO6SBeZnFmpQMc=,tag:MDVn5XyakMDrqMWnbEiU7A==,type:str]
            #ENC[AES256_GCM,data:hkdwR7OLerh4k5+aYdSaYzXmV7ugk/hbdtVJaFQ=,iv:yE3OAIelFskY0JyKszti0OVfqSmgGieyzCUnPuv6cfo=,tag:Dt0AIyUvf7pStiFQ5SWRhA==,type:comment]
            SQL_PASSWORD: ENC[AES256_GCM,data:YKz2pFL32bhY/JLa4Hr8DIHaEMo=,iv:1c+ik+ZGjoLhMpTctW88zHjQJinA4u5KaPoC4hbKCmw=,tag:pp0IjUkKptZIDh/VFujyKg==,type:str]
sops:
    age:
        - recipient: age1fguh0tj0gmh879mgxaeseyzxtx7chsw5he7x6ngkglg24p2h2elqrez9hf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoN0hubS9xUjVEZ0lyTjM3
            MTdidUE5blJBc1UveVZuRVJUb1pFRnVrLzJFCkRJRndjc1dKQnBFdWNFZXoyQVI5
            N1ZIU1FMUWdsWnZ0YlVWUkg2cnBXbW8KLS0tIDN0UEdLQ050dGVSMlJha3N6ci91
            N3VxRC80b0RlVDNHaW1vV21wVEdRTEEKbPM1v/LzMyMt6iOguZftFipZq8uQVdZB
            SO3yu9dlDsNN4dXLwH2+M6q3xWWzK5TLhevedbvXICqPdkrCGG9L+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T15:18:34Z"
    mac: ENC[AES256_GCM,data:6RmQHdtrGvT5GTVeMNj0xXGpeTkxUbDx81GIC6DU1hkYNfz+RcNqVvqUcILwkEexr/D8xG2KmIOT6O9DQtui9qjeTUH0w4AXdLcjWwkPSb1g/x3HXvCszJZpDB146C5uu8fXDwlw+rsEiaw0r07rZnAWi347bPUxX+jn4hgWrpU=,iv:6LGBz1bjTcPgbjquvR+Lh0tYON8OtUD6dl5ZTpCE0ec=,tag:2CKpZOnnQ/A7z/OlernttQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
