applications:
    agentic-backend:
        configuration:
            ai:
                default_chat_model:
                    settings:
                        default_headers:
                            Authorization: ENC[AES256_GCM,data:ZxVggPCwFvK18+B3GHCTOVenCvR9XhGNN48ovHwYCUJiyd6Appwt,iv:m4stOYvk6WvL3RzdJqdZTNRRljiywJqZnPOfghHqOqE=,tag:hEF55mZ951+N1JyTlpksaQ==,type:str]
        dotenv:
            OPENSEARCH_PASSWORD: ENC[AES256_GCM,data:ccupup0mW3VH1GKPmyC5akVLcQ==,iv:xcF8KnlY0wHHddMGx1igmyzih6QY53jbRo9rA8qoC4k=,tag:/BeUc9jQ/E62eaZPe/IgLQ==,type:str]
            #ENC[AES256_GCM,data:S5xB8mA2nsyS1BKf7ksmSr43tvVLr2LwR9c00jOKaKPDsgMcq1CwTn313bY=,iv:RlVIybrzKbJxZPiL7hmhyJhR18vYDgYCH/zzmULjp2Q=,tag:UXUL2DgQqh7l3dovaEb7lA==,type:comment]
            OPENAI_API_KEY: ENC[AES256_GCM,data:sY6+xPzv0MuOuwXx9EVZvdTMY87RO1/AGzkZkPIfc8o=,iv:ulNkE2YQaEiG30Qj/Sf8mHhmxUPKvfI/FTwL31bw/HY=,tag:vRR1CZYm7dFdcgeQKz2Osg==,type:str]
            KEYCLOAK_AGENTIC_CLIENT_SECRET: ENC[AES256_GCM,data:xbbbrCGxxZ71rvQpkjl5U7nFHf1j5L2TcCYpC06/NDE=,iv:fjrCB6QEYIv78xdMaA9bX8vTPn4MfkJBuz6ZyDWwasE=,tag:N3u+y8U05sLLNwD+U+stuw==,type:str]
            M2M_CLIENT_SECRET: ENC[AES256_GCM,data:mqPG2OEn6Akg5Sbjj6yzppYNKnH77Ut9H1jYroB+CL0=,iv:xdcJM9KFZnqWRJFZsQIKbTB3bRok9EeIkOhZxgwQzrk=,tag:g0PwtsdXQgCXF9Ully5qaQ==,type:str]
            OPENFGA_API_TOKEN: ENC[AES256_GCM,data:XdeXsKXVPQFFTliMRyylarydwuY=,iv:2L+rDzA9SDYDNDpE725NpXV5NalsFSV4a+1qbfVMTAI=,tag:oYRtqLH/GmwnxlhItH/0pw==,type:str]
    knowledge-flow-backend:
        configuration:
            chat_model:
                settings:
                    default_headers:
                        Authorization: ENC[AES256_GCM,data:ZKyhNBmI3gJ0JEuLwVXWH9Tx91NTre6fgBvd+XZi6BiR2mqZ1tW2,iv:wdzxDROwEbPtiK1piBhy1VVdHbBDCD5vmF2p8dNVUf0=,tag:2myQdU1k2qkjgOqo6khx2A==,type:str]
            embedding_model:
                settings:
                    default_headers:
                        Authorization: ENC[AES256_GCM,data:BruIB3RACI7uXPUwCnDTB5kQfDlH42M15VZlWZaEtXcAZY4gFCQm,iv:4YSHKS2SHn++8cLtgdDsKb8X1zCuYWB1jUhoMrTvfT8=,tag:lOomdxAnyd3O7XQGqeaBqg==,type:str]
        dotenv:
            OPENSEARCH_PASSWORD: ENC[AES256_GCM,data:bVoVdx+/Dp+DWlMpa433aYe/QQ==,iv:AenTqtcA+4Hhmdj8J2/L97zF2+JNqHS525y3X+bt+Kc=,tag:feWd7a+xmQqF+jxXlx2xLw==,type:str]
            #ENC[AES256_GCM,data:cYkUmY8t73p8T54+HAWnjnKaymt9PGp9keW0n/9iDTMp0dwmg6XfYi6AMJg=,iv:td4S0kl07xRhGJaLkkfO6iG18ZfgoN3Zu+SOO4jZXEA=,tag:zw5Jyr5wONAhpfynXu+BJQ==,type:comment]
            OPENAI_API_KEY: ENC[AES256_GCM,data:MDNqP+ub9ABUtetVsx/TorKuloNmHF+tz6bWbHcUy8I=,iv:UWFm0DfOEUe0SEO81pNM7O4wUmpxe+b426eJr4y1NuY=,tag:O0hfcJKOx0lDJnbOmlNaaw==,type:str]
            KEYCLOAK_KNOWLEDGE_FLOW_CLIENT_SECRET: ENC[AES256_GCM,data:j2sG1nv/E2w4Mu4i5iro28leEHyZw9RaSR1bRHbkaXY=,iv:/VySCTLu7nefUvi4oDpsVE9I2byynpKI81dEeqvWmwQ=,tag:64H50GfuLl6rZN5EGp/JoA==,type:str]
            MINIO_SECRET_KEY: ENC[AES256_GCM,data:4OhwdLBAr+a95FQzei4tWDW5PSw=,iv:QfNi3AXTw5G87vyVvjgUIWGmB7T2DpJTcNtnbKrl+QQ=,tag:5mp0AVK+y2z4tWdI9+Fxfg==,type:str]
            OPENFGA_API_TOKEN: ENC[AES256_GCM,data:Q1n/Igo16hZ8/kjptPtH1QSrVtw=,iv:J82sf2j+Hp/8bwW32rwyxCwTMk3t5BK3V1+SXKMy+ck=,tag:knmIACxAyqNHw37B82Smig==,type:str]
sops:
    age:
        - recipient: age1fguh0tj0gmh879mgxaeseyzxtx7chsw5he7x6ngkglg24p2h2elqrez9hf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6WjhYVThNRDgrYVRyejNX
            aEdiRDZwT2grY3VzWTIxTmZreXNTcTloQVNjCnlVWUZ4Y1BmOUtrMVhVUVUzbTdT
            S2ErcjJLZnVsRytiZ3JjL0xOTTJLUEkKLS0tIHU3Q1JmZ29yOUhCUVFEUy9VTS9K
            cWlUU3lLelIvQjFoVDRmL0RESG4zUU0KWb6HB+dO3lVPdwZ7v5PdtQvjLMs+3DOl
            aG9tlDJcZ8qN0xxmJgqsZ8LV0KfFF5nXvG1Ieu/AqVXGzNRUkhAu+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T14:49:36Z"
    mac: ENC[AES256_GCM,data:k0WXNKUZ7LLn9Mv4kcW+bKVjzxji1MVPnlxDyUoORKKTB3Ymnf3+myJseamaphroQUaDDyoU2N+9bH6rKlz7saU2YbZtHx5bAvy8csQLoxXrvKda0WpNraTCwF10nD8WexdkT0HbzHZjoqyKVUkzoWob9qDmfeojYPur+U9BoRc=,iv:qx6MgyuMo9mXx5X5cfOpF+X1KtREtNiDeuJ4svasuXc=,tag:cmH8x2vmcOAwJlJGTojnJw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
