applications:
    agentic-backend:
        configuration:
            ai:
                default_chat_model:
                    settings:
                        default_headers:
                            Authorization: ENC[AES256_GCM,data:42deJvjw7fgjvW+91r/3oXuOeOjczkbtfq/zz1oX+rBbNNHpwVPk,iv:3pd+OOOME7jFniXCgAeNGTx6HvZEH+BPSUYi5qU+B/M=,tag:ZA0NqbGnQEqh3a4TyNz/cg==,type:str]
        dotenv:
            OPENSEARCH_PASSWORD: ENC[AES256_GCM,data:fnGmye0FCJSEx3BWt9+Cl+hHIQ==,iv:n08CXfDUC8vZwWOLtubE5/73BjEpuusZTWapTQCI/0s=,tag:e83KbA6OzsXeUWN3mFM7hg==,type:str]
            #ENC[AES256_GCM,data:7UIbkbOrnLSxMAtRuIOEBgL9vuC9ySfzuIjMrbm3W4/P3r870esu/QTyvIc=,iv:ocu3Hw2RpjJlkL6BZQDjTbRIylxiyKSOOHFlWJi1nLA=,tag:4P0XX608rw7l/DWsWVj6Aw==,type:comment]
            OPENAI_API_KEY: ENC[AES256_GCM,data:p0cM0oi4BeL7mA1riLt8qzdVn30FWPTzKC1GxKuxwDg=,iv:HK5s2auxVJxuv7Xz44aRImE2PEJ3zuwK+QP1Ubz3Q+I=,tag:ZLAbium0isjyQNUXPjsz1A==,type:str]
            KEYCLOAK_AGENTIC_CLIENT_SECRET: ENC[AES256_GCM,data:D/DOAAYr+B1Gkms7ugcIcRy3837aAO2a8U0qci4PiPw=,iv:u0i3JDNqj3SlabX4TvQQ53kRxDia5vUL2/6iVwvmlRg=,tag:Bg2n/eYrHxJCS94x7BzLow==,type:str]
            M2M_CLIENT_SECRET: ENC[AES256_GCM,data:KXQI/z7KKBsdWNVayuMfQDI9NViTo1GzRg+2ULclGCs=,iv:/7BF/Rs4qkZwGIeBzo8MKBaqG9JZIhj4RmCfEzuH5Zs=,tag:z0/lCvlvJsFy0V9uw24ujA==,type:str]
            OPENFGA_API_TOKEN: ENC[AES256_GCM,data:/OzB1WXStPxE2mnWkVYK//MUJQM=,iv:XfYZWvidL0nt6DSVr98316sjHesRrPPCsTpTOcR56p0=,tag:c5mllHftgNj/lMDqgeU8uA==,type:str]
            #ENC[AES256_GCM,data:lj0cE1S9v9YIJ20THf+zagWMsgn3h2fMMsua3KE=,iv:dOmuTkLcF7zSP6pawWV0xqwdrAX/G8WoZXyKsUbTnco=,tag:3ZcUkC62wtwb2PYpgwsS+g==,type:comment]
            POSTGRES_PASSWORD: ENC[AES256_GCM,data:oF5aOQoGsK+MyRWRK3d/Zb/q5Is=,iv:pjlEcGb/V0096IMCCuntw4mcgP6ftqqctvrNjQrn8g8=,tag:69FawTisxUAexD5O5KqKPA==,type:str]
    knowledge-flow-backend:
        configuration:
            chat_model:
                settings:
                    default_headers:
                        Authorization: ENC[AES256_GCM,data:V3YUQTVnqIBvg8/4ONstTfYdNn1kuSEUS8KoVxTejEoQHV3jKtqn,iv:FIFrVhCrFzJyVwYznnPWZ6pd/zXtg8vD1gygKXNFMoM=,tag:2ZXoxQsjJG9rtEsw/dh32A==,type:str]
            embedding_model:
                settings:
                    default_headers:
                        Authorization: ENC[AES256_GCM,data:wuztOHaH/Vatz5L4G8gf8YDI4yeSVRu4q1Tl+37JsXUVGQrhmNSq,iv:KRbKLOwm2pf6FcoI2/P1L4G5lBsdiYVztZuVtK1QA9Q=,tag:5p51N55T4q4BsMefY8dbpw==,type:str]
        dotenv:
            OPENSEARCH_PASSWORD: ENC[AES256_GCM,data:1Ty6lo+cyvix13BjKvwTJamuvA==,iv:v0TsbYCtZ6esNIQlq2iADhJZpwYJHRsaXbhvMr5x8Kg=,tag:c0jBaGaqZDIkAi+bz/urAg==,type:str]
            #ENC[AES256_GCM,data:+wpTjfxU5MgXahnvl2gCk8Ekr/IZ5OGllUnrTGUwGvLu6V/sPBUm9mHqX/Q=,iv:Q9sCFJf2pMmUvfHWdn1jwZWuuxvmiyDK4sN25t14x6I=,tag:glzvNq8yaB2kcpzaTFO5gA==,type:comment]
            OPENAI_API_KEY: ENC[AES256_GCM,data:+pbA0cdRt5BanGrAKeQXdL+uZgdtVq8aw/ivwSIQk7g=,iv:c6FY37Vkm7X7MbF0I8hbVQRqWanHcEp7DEO2dAD5o9U=,tag:u8cUfVGockNl7gJCfovzSA==,type:str]
            KEYCLOAK_KNOWLEDGE_FLOW_CLIENT_SECRET: ENC[AES256_GCM,data:uaTUu97e2FGTEUk0lsJqR4tszICTiDs0vyfcaL2bwHE=,iv:c4kyxgIDDZ6RKVlsIts5ypyOirLhXMVmCOsTMkneo8E=,tag:aUaJtFKwA0euL+5FcNuWhw==,type:str]
            MINIO_SECRET_KEY: ENC[AES256_GCM,data:vs7rOeOLUPytCn6hHA/PWGEwxbw=,iv:vD/hxs4IkdTxVFh+rRE2txl8+OO9nSkiRYXbcGprgQc=,tag:gYxW/BaigB2eBOE28sEg0Q==,type:str]
            OPENFGA_API_TOKEN: ENC[AES256_GCM,data:2dSKZ+Mexo0ALDzj/8/fEjgvidQ=,iv:SKRRdzqGAsUKQ5OOaLHA6Xgydj0T4L0HP5ZxWBqJtY4=,tag:9kiS4yiLvL3AP9jWf07DDQ==,type:str]
            #ENC[AES256_GCM,data:O+9WbwN79PzGLnsBeF6CUGias59QQMhrFIgtgWc=,iv:dHch6PTKhrDDjsSjQARK9Tor5Wcb79N/QSXFlXRAVWY=,tag:FXqKZPgcG8VtloEDFwKRvA==,type:comment]
            POSTGRES_PASSWORD: ENC[AES256_GCM,data:6OhWyqEIL5c2lkN4j2mGB9Lv4PI=,iv:6K1pfDSfBW9xRuT9g1koVBrp2zZ10U6wxKnWVg5Na/M=,tag:WKSnVUcSLwIdTU8xA3D6Dw==,type:str]
            #ENC[AES256_GCM,data:wfPQUeyY/KylXuf4p8noMkjfcFRHlxpHD1ZovmI=,iv:CueEOsMe6cNEDb83FM/feRPDWJ0RT56yXehm8Lcvb44=,tag:TWzkQ5RD1VnS6QwG+LS46Q==,type:comment]
            SQL_PASSWORD: ENC[AES256_GCM,data:Jt+o2gpR3o1U0UZS9Leb5/rcBr0=,iv:gxFqRt6pgBe+q4YM8Slriv+Bnnntzj9amVlzjT2w+IU=,tag:vw8iTH4KswW9Q4EH5kv/lQ==,type:str]
sops:
    age:
        - recipient: age1fguh0tj0gmh879mgxaeseyzxtx7chsw5he7x6ngkglg24p2h2elqrez9hf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwcjM2OWRsNnlqSCtLTCti
            TFJDcE12NmcyazVqc1g1bXF0WUozd1piQW5FCm5ZMVBsNE5zQUlCUTFRa1NVY1c2
            QkZjN0NJZXR6cWtheXFzRDdtT3BwaUUKLS0tIG4xNktubHRKcXhCTHg0eW1LOE5B
            S0svT3FJVFlqSm9WWkxIWWwrdnRCZVEKhZziCuwkWkqM3rHD/mkplXrsaD/sbeUH
            1OqIIAjSOHab09E6TtnERM3Vpp932sNtrJ9bWTpM1wD0LiFJoITljA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-27T16:30:59Z"
    mac: ENC[AES256_GCM,data:HmKeSQbytlCGfr+jTVE45Dusf46HyjISTQGyIe2dzxtuxxdi7NgZFQnkp0jWo2OQ+HcPMLRaYkFJbyNVGBNXeU5I7OpDry5RV8Pxr9cJ79M0OsEouBTMyAqjefWYL4cLmdSdBiNE+EEoZUqYgrD7IafaLYzb3cGkoGeSzXFDNOw=,iv:nv4gtYUXCoQf/VlQ9jbyJ/ppLRTI8eHVGJF/qbOQcck=,tag:Sfw5zTfwSBhjqNaJc22EUA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
