environments:
  prd:
    values:
      - namespace: dc2-wd1-six-prd-kns-pri
  int:
    values:
      - namespace: dc2-wd1-six-int-kns-pri
---
helmDefaults:
  createNamespace: false
  wait: true

releases:
  - name: fred
    namespace: "{{ .Values.namespace }}"
    chart: ../../charts/fred
    values:
      - values/{{ .Environment.Name }}/values-fred.yaml
    secrets:
      - values/{{ .Environment.Name }}/values-fred.sec.yaml
