# spe frontend

imagePullSecretName: []
ingress:
  enabled: true
  className: "traefik"
  annotations: {}
  hosts:
    - host: fred.test
      paths:
        - path: /
  tls:
    - secretName: fred-frontend-crt
      hosts:
        - fred.test

config:
  backendUrlApi: "http://fred-backend.test"
  websocketUrl: "ws://fred-backend.test/fred/chatbot/query"

env:
  - name: VITE_ALLOWED_HOSTS
    value: "fred.test"
  - name: VITE_BACKEND_URL_KNOWLEDGE
    value: "http://knowledge-flow-backend.test"
  - name: VITE_USE_AUTH
    value: "true"

oidc:
  config:
    realm: "app"