apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.applicationName }}-configmap"
  namespace: {{ .Release.Namespace }}
data:
  configuration.yaml: |
{{ .Values.configuration | toYaml | indent 4 }}

  .env: |
    {{- range $key, $value := .Values.dotenv }}
    {{- if $value }}
    {{ $key }}="{{ $value }}"
    {{- else }}
    {{ $key }}=""
    {{- end }}
    {{- end }}
