apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.applicationName }}-configmap"
  namespace: {{ .Release.Namespace }}
data:
  configuration.yaml: |
    security:
      enabled: {{ .Values.configuration.security.enabled }}
      keycloak_url: "{{ .Values.configuration.security.keycloak_url }}"
      authorized_origins:
      {{- range .Values.configuration.security.authorized_origins }}
        - "{{ . }}"
      {{- end }}

    input_processors:
    {{- range .Values.configuration.input_processors }}
      - prefix: "{{ .prefix }}"
        class_path: "{{ .class_path }}"
    {{- end }}

    {{- if .Values.configuration.output_processors }}
    output_processors:
    {{- range .Values.configuration.output_processors }}
      - prefix: "{{ .prefix }}"
        {{- if .class_path }}
        class_path: "{{ .class_path }}"
        {{- end }}
    {{- end }}
    {{- end }}

    content_storage:
      type: "{{ .Values.configuration.content_storage.type }}"

    metadata_storage:
      type: {{ default "opensearch" .Values.configuration.metadata_storage.type | quote }}
      {{- if eq .Values.configuration.metadata_storage.type "opensearch" }}
      host: {{ default "https://opensearch.dev.svc.cluster.local:9200" .Values.configuration.metadata_storage.host | quote }}
      secure: {{ default true .Values.configuration.metadata_storage.secure }}
      verify_certs: {{ default false .Values.configuration.metadata_storage.verify_certs }}
      metadata_index: {{ default "metadata-index" .Values.configuration.metadata_storage.metadata_index | quote }}
      vector_index: {{ default "vector-index" .Values.configuration.metadata_storage.vector_index | quote }}
      {{- end }}

    vector_storage:
      type: {{ default "opensearch" .Values.configuration.vector_storage.type | quote }}
      {{- if eq .Values.configuration.vector_storage.type "opensearch" }}
      host: {{ default "https://opensearch.dev.svc.cluster.local:9200" .Values.configuration.vector_storage.host | quote }}
      secure: {{ default true .Values.configuration.vector_storage.secure }}
      verify_certs: {{ default false .Values.configuration.vector_storage.verify_certs }}
      metadata_index: {{ default "metadata-index" .Values.configuration.vector_storage.metadata_index | quote }}
      vector_index: {{ default "vector-index" .Values.configuration.vector_storage.vector_index | quote }}
      {{- else if eq .Values.configuration.vector_storage.type "weaviate" }}
      host: {{ default "http://localhost:8080" .Values.configuration.vector_storage.host | quote }}
      index_name: {{ default "CodeDocuments" .Values.configuration.vector_storage.index_name | quote }}
      {{- end }}

    embedding:
      type: "{{ .Values.configuration.embedding.type }}"

    knowledge_context_storage:
      type: "{{ .Values.configuration.knowledge_context_storage.type }}"
      local_path: "{{ .Values.configuration.knowledge_context_storage.local_path }}"

    knowledge_context_max_tokens: {{ .Values.configuration.knowledge_context_max_tokens }}


  .env: |
    # This file contains the environment variables for the application

    # -----------------------------------------------------------------------------
    # 🔵 AZURE AUTHENTICATION (for getting OAuth token)
    # -----------------------------------------------------------------------------
    AZURE_TENANT_ID="{{ .Values.dotenv.AZURE_TENANT_ID }}"
    # Azure Active Directory Tenant ID for your application (OAuth 2.0 flow)

    AZURE_CLIENT_ID="{{ .Values.dotenv.AZURE_CLIENT_ID }}"
    # Client ID of your registered Azure AD Application (Service Principal)

    AZURE_CLIENT_SECRET="{{ .Values.dotenv.AZURE_CLIENT_SECRET }}"
    # Client Secret of your Azure AD Application

    AZURE_CLIENT_SCOPE="{{ .Values.dotenv.AZURE_CLIENT_SCOPE }}"
    # OAuth2 scope for requesting tokens

    # -----------------------------------------------------------------------------
    # 🔵 AZURE API SETTINGS
    # -----------------------------------------------------------------------------
    AZURE_API_VERSION="{{ .Values.dotenv.AZURE_API_VERSION }}"
    # API version used for Azure OpenAI API requests

    # -----------------------------------------------------------------------------
    # 🔵 API GATEWAY (APIM) SETTINGS
    # -----------------------------------------------------------------------------
    AZURE_APIM_BASE_URL="{{ .Values.dotenv.AZURE_APIM_BASE_URL }}"
    # Base URL of your Azure API Management Gateway (APIM)

    AZURE_RESOURCE_PATH_EMBEDDINGS="{{ .Values.dotenv.AZURE_RESOURCE_PATH_EMBEDDINGS }}"
    # Path after base URL for Embeddings API

    AZURE_RESOURCE_PATH_LLM="{{ .Values.dotenv.AZURE_RESOURCE_PATH_LLM }}"
    # Path after base URL for LLM Chat API

    AZURE_APIM_KEY="{{ .Values.dotenv.AZURE_APIM_KEY }}"
    # Subscription Key required by the APIM Gateway

    # -----------------------------------------------------------------------------
    # 🔵 AZURE OPENAI DIRECT SETTINGS
    # -----------------------------------------------------------------------------
    AZURE_OPENAI_BASE_URL="{{ .Values.dotenv.AZURE_OPENAI_BASE_URL }}"
    # Direct access to Azure OpenAI resource

    AZURE_OPENAI_API_KEY="{{ .Values.dotenv.AZURE_OPENAI_API_KEY }}"
    # Azure OpenAI API Key

    # -----------------------------------------------------------------------------
    # 🔵 AZURE OPENAI DEPLOYMENT NAMES
    # -----------------------------------------------------------------------------
    AZURE_DEPLOYMENT_LLM="{{ .Values.dotenv.AZURE_DEPLOYMENT_LLM }}"
    # LLM deployment name

    AZURE_DEPLOYMENT_EMBEDDING="{{ .Values.dotenv.AZURE_DEPLOYMENT_EMBEDDING }}"
    # Embedding model deployment name

    # -----------------------------------------------------------------------------
    # 🔵 OPENAI (Public API)
    # -----------------------------------------------------------------------------
    OPENAI_API_KEY="{{ .Values.dotenv.OPENAI_API_KEY }}"
    # Your OpenAI API Key

    OPENAI_API_VERSION="{{ .Values.dotenv.OPENAI_API_VERSION }}"
    # API version (optional)

    # -----------------------------------------------------------------------------
    # 🔵 OLLAMA SETTINGS
    # -----------------------------------------------------------------------------
    OLLAMA_API_URL="{{ .Values.dotenv.OLLAMA_API_URL }}"
    OLLAMA_EMBEDDING_MODEL_NAME="{{ .Values.dotenv.OLLAMA_EMBEDDING_MODEL_NAME }}"
    OLLAMA_VISION_MODEL_NAME="{{ .Values.dotenv.OLLAMA_VISION_MODEL_NAME }}"

    # -----------------------------------------------------------------------------
    # 🔵 KEYCLOAK SETTINGS
    # -----------------------------------------------------------------------------
    KEYCLOAK_SERVER_URL="{{ .Values.dotenv.KEYCLOAK_SERVER_URL }}"
    KEYCLOAK_REALM_NAME="{{ .Values.dotenv.KEYCLOAK_REALM_NAME }}"
    KEYCLOAK_CLIENT_ID="{{ .Values.dotenv.KEYCLOAK_CLIENT_ID }}"

    # -----------------------------------------------------------------------------
    # 🔵 OPENSEARCH SETTINGS
    # -----------------------------------------------------------------------------
    OPENSEARCH_USER="{{ .Values.dotenv.OPENSEARCH_USER }}"
    OPENSEARCH_PASSWORD="{{ .Values.dotenv.OPENSEARCH_PASSWORD }}"

    # -----------------------------------------------------------------------------
    # 🔵 MINIO
    # -----------------------------------------------------------------------------
    MINIO_ENDPOINT="{{ .Values.dotenv.MINIO_ENDPOINT }}"
    MINIO_ACCESS_KEY="{{ .Values.dotenv.MINIO_ACCESS_KEY }}"
    MINIO_SECRET_KEY="{{ .Values.dotenv.MINIO_SECRET_KEY }}"
    MINIO_BUCKET_NAME="{{ .Values.dotenv.MINIO_BUCKET_NAME }}"
    MINIO_SECURE={{ .Values.dotenv.MINIO_SECURE }}

    # -----------------------------------------------------------------------------
    # 🔵 GCS
    # -----------------------------------------------------------------------------
    GCS_CREDENTIALS_PATH={{ .Values.dotenv.GCS_CREDENTIALS_PATH }}
    GCS_BUCKET_NAME={{ .Values.dotenv.GCS_BUCKET_NAME }}
    GCS_PROJECT_ID={{ .Values.dotenv.GCS_PROJECT_ID }}

    # -----------------------------------------------------------------------------
    # 🔵 LOCAL STORAGE
    # -----------------------------------------------------------------------------
    LOCAL_CONTENT_STORAGE_PATH="{{ .Values.dotenv.LOCAL_CONTENT_STORAGE_PATH }}"
    LOCAL_METADATA_STORAGE_PATH="{{ .Values.dotenv.LOCAL_METADATA_STORAGE_PATH }}"


