VERSION=0.1.0
PROJECT_NAME=fred-agentic-backend
PY_PACKAGE=app

PORT ?= 8000
include ../scripts/makefiles/python-vars.mk

include ../scripts/makefiles/python-deps.mk
include ../scripts/makefiles/python-run.mk
include ../scripts/makefiles/python-openapi.mk
include ../scripts/makefiles/python-code-quality.mk
include ../scripts/makefiles/python-test.mk
include ../scripts/makefiles/python-clean.mk
include ../scripts/makefiles/help.mk
