variables:
  CODE_DOCKER_TAG:
    value: "0.0.4-prism"
    description: "Version tag for code docker images (used for manual builds)."
  BUILD_CODE_DOCKER_IMAGE:
    value: "true"
    options: ["true", "false"]
    description: "Defines if code docker images (frontend, agentic-backend, knowledge-flow-backend) must be built"
  BENCHMARK_DOCKER_TAG:
    value: "0.0.4-prism"
    description: "Version of benchmark tools docker image."
  BUILD_BENCHMARK_DOCKER_IMAGE:
    value: "false"
    options: ["true", "false"]
    description: "Defines if benchmark tools docker image must be built"

# -----------------------------------------------------------------------------
# Stages definition, order and workflow conditions
# -----------------------------------------------------------------------------

stages:
  - build-image

workflow:
  rules:
    - if: $CI_COMMIT_TAG =~ /^code\/v\d+\.\d+\.\d+$/
    - if: $CI_PIPELINE_SOURCE == "web"

# -----------------------------------------------------------------------------
# Build docker images
# -----------------------------------------------------------------------------

.docker-auth: &docker-auth
  - CI_REGISTRY_AUTH="$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')"
  - |
    cat << EOF > /kaniko/.docker/config.json
    {
      "auths": {
        "${CI_REGISTRY}": {
          "auth": "${CI_REGISTRY_AUTH}"
        }
      }
    }
    EOF

.docker-default:
  image: gcr.io/kaniko-project/executor:v1.23.2-debug
  stage: build-image
  before_script: *docker-auth
  script:
    - |
      echo CONTEXT = ${CONTEXT}
      echo DOCKER_FILE = ${DOCKER_FILE}
      echo CI_REGISTRY_IMAGE = ${CI_REGISTRY_IMAGE}
      echo IMAGE_NAME = ${IMAGE_NAME}
      echo IMAGE_TAG = ${IMAGE_TAG}
      /kaniko/executor --context ${CONTEXT} --dockerfile ${CONTEXT}/${DOCKER_FILE} --destination ${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:${IMAGE_TAG}

.docker-code:
  extends: .docker-default
  rules:
    - if: '$CI_COMMIT_TAG =~ /^code\/v\d+\.\d+\.\d+$/'
    - if: $BUILD_CODE_DOCKER_IMAGE == "true"
  before_script:
    - *docker-auth
    - |
      if [ -n "${CI_COMMIT_TAG}" ]; then
        IMAGE_TAG=$(echo "${CI_COMMIT_TAG}" | sed 's|^code/v||')
        export IMAGE_TAG
      fi

docker-frontend:
  extends: .docker-code
  variables:
    IMAGE_NAME: frontend
    IMAGE_TAG: ${CODE_DOCKER_TAG}
    CONTEXT: ${CI_PROJECT_DIR}
    DOCKER_FILE: frontend/dockerfiles/Dockerfile-prod

docker-backend-api:
  extends: .docker-code
  variables:
    IMAGE_NAME: agentic-backend
    IMAGE_TAG: ${CODE_DOCKER_TAG}
    CONTEXT: ${CI_PROJECT_DIR}
    DOCKER_FILE: agentic-backend/dockerfiles/Dockerfile-prod

docker-backend-knowledge:
  extends: .docker-code
  variables:
    IMAGE_NAME: knowledge-flow-backend
    IMAGE_TAG: ${CODE_DOCKER_TAG}
    CONTEXT: ${CI_PROJECT_DIR}
    DOCKER_FILE: knowledge-flow-backend/dockerfiles/Dockerfile-prod

docker-benchmark:
  extends: .docker-default
  variables:
    IMAGE_NAME: benchmark-tools
    IMAGE_TAG: ${BENCHMARK_DOCKER_TAG}
    CONTEXT: ${CI_PROJECT_DIR}/developer_tools/benchmarks
    DOCKER_FILE: Dockerfile
  rules:
    - if: $BUILD_BENCHMARK_DOCKER_IMAGE == "true"

# # -----------------------------------------------------------------------------
# # Manage helm charts with kastctl
# # -----------------------------------------------------------------------------

# .kastctl-default:
#   image: ${GITLAB_CICD_DOCKER_IMAGE}:${GITLAB_CICD_DOCKER_TAG}
#   before_script:
#     - echo

# kastctl-install:
#   extends: .kastctl-default
#   stage: kastctl-install
#   script:
#     - helm repo add kast ${KAST_REPO_URL} --username ${KAST_REPO_USER} --password ${KAST_REPO_PASSWORD}
#     - kubectl create ns bidgpt --dry-run=client -o yaml 2> /dev/null | kubectl apply -f -
#     - kubectl -n bidgpt create secret docker-registry gitlab-registry-creds --docker-username=${CI_REGISTRY_USER} --docker-password=${CI_REGISTRY_PASSWORD} --docker-server=${CI_REGISTRY} --dry-run=client -o yaml 2> /dev/null | kubectl apply -f -
#     - kastctl pass --init --token ${KAST_DEPLOY_TOKEN}
#     - kastctl pass --add backend.AZURE_CLIENT_SECRET:${AZURE_CLIENT_SECRET} --token ${KAST_DEPLOY_TOKEN}
#     - kastctl pass --add backend.AZURE_APIM_KEY:${AZURE_APIM_KEY} --token ${KAST_DEPLOY_TOKEN}
#     - kastctl install --kpack kpack-tdf.yaml --kpack-path ${CI_PROJECT_DIR}/deploy/helm --deployment-path ${CI_PROJECT_DIR}/deploy/helm --token ${KAST_DEPLOY_TOKEN}
#   rules:
#     - if: $KASTCTL == "install"

# kastctl-uninstall:
#   extends: .kastctl-default
#   stage: kastctl-uninstall
#   script:
#     - kastctl uninstall --kpack kpack-tdf.yaml --kpack-path ${CI_PROJECT_DIR}/deploy/helm
#   rules:
#     - if: $KASTCTL == "uninstall"
