---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.kubernetesRole.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ .Values.kubernetesRole.kind }}
  name: {{ .Values.kubernetesRole.name }}
subjects:
- kind: ServiceAccount
  name: default
