{{- define "common-library.configmap-backend" }}

{{- if .Values.configuration_type.backend.enabled }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.applicationName }}-back"
  namespace: {{ .Release.Namespace }}
data:
  configuration.yaml: |
{{ .Values.configuration | toYaml | indent 4 }}

  .env: |
    {{- range $key, $value := .Values.dotenv }}
    {{- if $value }}
    {{ $key }}="{{ $value }}"
    {{- else }}
    {{ $key }}=""
    {{- end }}
    {{- end }}

{{- end }}

{{- end -}}