{{- define "common-library.deployment" }}

{{- if .Values.deployment.enabled }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.applicationName }}
  labels:
    app: {{ .Values.applicationName }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
  revisionHistoryLimit: {{ .Values.spec.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ .Values.applicationName }}
  template:
    metadata:
      annotations:
        {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
        # BEGIN - Force refresh of the deployment when configmap is changed
        {{- if .Values.configuration }}
        configmap.configurations.checksum: "{{ .Values.configuration | join "," | sha256sum }}"
        {{- end }}
        {{- if .Values.kubeconfig.enabled }}
        configmap.kubeconfig.checksum: "{{ .Values.kubeconfig.data | join "," | sha256sum }}"
        {{- end }}
        # END - Force refresh of the deployment when configmap is changed
      labels:
        app: {{ .Values.applicationName }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}

      {{- if .Values.serviceAccount.enabled }}
      serviceAccount: {{ .Values.serviceAccount.name }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- end }}

      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
        - name: {{ .Values.applicationName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ default "IfNotPresent" .Values.image.pullPolicy }}

          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          ports:
          {{- range .Values.ports }}
          - containerPort: {{ .containerPort }}
            {{- if .name }}
            name: {{ .name }}
            {{- end }}
          {{- end }}

          {{- if .Values.command.enabled }}
          command:
            {{- toYaml .Values.command.data | nindent 12 }}
          {{- end }}

          {{- if .Values.env.enabled }}
          env:
            {{- toYaml .Values.env.data | nindent 12 }}
            {{- if .Values.env.extraEnvVars }}
            {{- toYaml .Values.env.extraEnvVars | nindent 12 }}
            {{- end }}
          {{- end }}

          {{- if .Values.livenessProbe.enabled }}  
          livenessProbe:
            {{- toYaml .Values.livenessProbe.data | nindent 12 }}  
          {{- end }}

          {{- if .Values.readinessProbe.enabled }}   
          readinessProbe:
            {{- toYaml .Values.readinessProbe.data | nindent 12 }}  
          {{- end }}

          {{- if .Values.startupProbe }}  
            {{- if .Values.startupProbe.enabled }}   
          startupProbe:
            {{- toYaml .Values.startupProbe.data | nindent 12 }}  
            {{- end }}
          {{- end }}

          {{- if .Values.volumeMounts.enabled }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts.data | nindent 12 }}
          {{- end }}

          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}

      {{- if .Values.priorityClass }}
      priorityClassName: {{ .Values.priorityClass.name }}
      {{- end }}

      {{- if .Values.volumes.enabled }}
      volumes:
        {{- toYaml .Values.volumes.data | nindent 8 }}
      {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

{{- end }}

{{- end -}}