{{- define "common-library.service" -}}

{{- if .Values.service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.applicationName }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
  {{- end }}
  labels:
    app: {{ .Values.applicationName }}
    {{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels.data | indent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.applicationName }}
  ports:
{{ toYaml .Values.service.port | nindent 2 }}
{{- end -}}


{{- end -}}