{{- if .Values.securityConfigFiles.oidcConfig.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: opensearch-security-config
type: Opaque
stringData:
  config.yml: |
    {{- tpl (.Files.Get "files/config.yml") . | nindent 4 }}
{{- end }}
{{- if .Values.securityConfigFiles.users }}
---
apiVersion: v1
kind: Secret
metadata:
  name: opensearch-security-internal-users
type: Opaque
stringData:
  internal_users.yml: |
    {{- tpl (.Files.Get "files/internal_users.yml") . | nindent 4 }}
{{- end }}
{{- if .Values.securityConfigFiles.roles.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: opensearch-security-roles
type: Opaque
stringData:
  roles.yml: |
    {{- .Values.securityConfigFiles.roles.content | nindent 4 }}
{{- end }}
{{- if .Values.securityConfigFiles.rolesMapping.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: opensearch-security-roles-mapping
type: Opaque
stringData:
  roles_mapping.yml: |
    {{- .Values.securityConfigFiles.rolesMapping.content | nindent 4 }}
{{- end }}