---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-env
stringData:
  .env: |
    # This file contains the environment variables for the application

    # -----------------------------------------------------------------------------
    # 🔵 AZURE AUTHENTICATION (for getting OAuth token)
    # -----------------------------------------------------------------------------

    AZURE_TENANT_ID="{{.Values.dotenv.azure_tenant_id}}"
    # Azure Active Directory Tenant ID for your application (OAuth 2.0 flow)

    AZURE_CLIENT_ID="{{.Values.dotenv.azure_client_id}}"
    # Client ID of your registered Azure AD Application (Service Principal)

    AZURE_CLIENT_SECRET="{{.Values.dotenv.azure_client_secret}}"
    # Client Secret of your Azure AD Application

    AZURE_CLIENT_SCOPE="{{.Values.dotenv.azure_client_scope}}"  
    # OAuth2 scope for requesting tokens (typically "https://cognitiveservices.azure.com/.default")


    # -----------------------------------------------------------------------------
    # 🔵 AZURE API SETTINGS
    # -----------------------------------------------------------------------------

    AZURE_API_VERSION="{{.Values.dotenv.azure_api_version}}"  
    # API version used for Azure OpenAI API requests (depends on your Azure resource)


    # -----------------------------------------------------------------------------
    # 🔵 API GATEWAY (APIM) SETTINGS
    # -----------------------------------------------------------------------------

    AZURE_APIM_BASE_URL="{{.Values.dotenv.azure_apim_base_url}}"  
    # Base URL of your Azure API Management Gateway (APIM)
    # Example: https://company-apim-gateway.azure-api.net

    AZURE_RESOURCE_PATH_EMBEDDINGS="{{.Values.dotenv.azure_resource_path_embeddings}}"  
    # Path after base URL for Embeddings API (before /deployments/...)

    AZURE_RESOURCE_PATH_LLM="{{.Values.dotenv.azure_resource_path_llm}}"  
    # Path after base URL for LLM Chat API (before /deployments/...)

    AZURE_APIM_KEY="{{.Values.dotenv.azure_apim_key}}"  
    # Subscription Key required by the APIM Gateway ("TrustNest-Apim-Subscription-Key" header)

    # -----------------------------------------------------------------------------
    # 🔵 AZURE OPENAI DIRECT SETTINGS (if AZURE_USE_APIM=false)
    # -----------------------------------------------------------------------------

    AZURE_OPENAI_ENDPOINT="{{.Values.dotenv.azure_openai_endpoint}}"
    # Base URL for direct Azure OpenAI access (no APIM)

    AZURE_OPENAI_API_KEY="{{.Values.dotenv.azure_openai_key}}"
    # Azure OpenAI API Key (directly from Azure portal, not APIM key)

    # -----------------------------------------------------------------------------
    # 🔵 AZURE OPENAI DEPLOYMENT NAMES
    # -----------------------------------------------------------------------------

    AZURE_DEPLOYMENT_LLM="{{.Values.dotenv.azure_deployment_llm}}"  
    # Deployment name in Azure OpenAI for Chat LLMs (ex: GPT-4 Turbo, GPT-4o)

    AZURE_DEPLOYMENT_EMBEDDING="{{.Values.dotenv.azure_deployment_embedding}}"  
    # Deployment name in Azure OpenAI for Embedding Models


    # -----------------------------------------------------------------------------
    # 🔵 OPENAI EMBEDDING (Public API - NOT Azure)
    # -----------------------------------------------------------------------------

    OPENAI_API_KEY="{{.Values.dotenv.openai_api_key}}"  
    # Your OpenAI API key from https://platform.openai.com/account/api-keys

    OPENAI_API_BASE="{{.Values.dotenv.openai_api_base}}"  
    # Optional. Defaults to https://api.openai.com/v1 for OpenAI public API

    OPENAI_API_VERSION="{{.Values.dotenv.openai_api_version}}"  
    # Leave blank for OpenAI public API (only needed for Azure)
    # Example (Azure only): "2024-06-01"

    # Example model for embeddings (default for OpenAI)
    OPENAI_MODEL_NAME="{{.Values.dotenv.openai_model_name}}"

    # KEYCLOAK
    KEYCLOAK_SERVER_URL="{{.Values.dotenv.keycloak_server_url}}"
    KEYCLOAK_REALM_NAME="{{.Values.dotenv.keycloak_realm_name}}"
    KEYCLOAK_CLIENT_ID="{{.Values.dotenv.keycloak_client_id}}"

    # LOCAL STORAGE
    LOCAL_CONTEXT_STORAGE_PATH="{{.Values.dotenv.local_context_storage_path}}"
    LOCAL_METADATA_STORAGE_PATH="{{.Values.dotenv.local_metadata_storage_path}}"

