name: Setup Python environment
description: Create a virtual environment and install dependencies with uv
inputs:
  working-directory:
    description: 'Working directory for the Python project'
    required: true
    default: '.'
runs:
  using: "composite"
  steps:
    - name: Set up uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true


    - name: Set up Python
      run: uv python install
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Install dependencies
      run: uv sync --locked  --all-extras --dev
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    
    - name: Minimize uv cache
      run: uv cache prune --ci
      shell: bash