name: Setup Python environment
description: Create a virtual environment and install dependencies with uv
inputs:
  working-directory:
    description: 'Working directory for the Python project'
    required: true
    default: '.'
runs:
  using: "composite"
  steps:
    - name: Set up uv
      uses: astral-sh/setup-uv@v6

    - name: Set up Python
      run: uv python install python
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Install dependencies
      run: uv sync --all-extras
      shell: bash
      working-directory: ${{ inputs.working-directory }}