_meta:
  type: "config"
  config_version: 2
config:
  dynamic:
    http:
      anonymous_auth_enabled: false
    authz: {}
    authc:
      basic_internal_auth_domain:
        description: "Authenticate via HTTP Basic against internal users database"
        http_enabled: true
        transport_enabled: true
        order: 1
        http_authenticator:
          type: "basic"
          challenge: false
        authentication_backend:
          type: "internal"
      openid_auth_domain:
        description: "Authenticate via OIDC (OpenID Connect)"
        http_enabled: true
        transport_enabled: true
        order: 0
        http_authenticator:
          type: "openid"
          challenge: false
          config:
            subject_key: "preferred_username"
            roles_key: {{ .Values.securityConfigFiles.oidcConfig.oidcRolesKey }}
            openid_connect_url: {{ .Values.securityConfigFiles.oidcConfig.oidcUrl }}
            client_id: {{ .Values.securityConfigFiles.oidcConfig.oidcClientId }}
            client_secret: {{ .Values.securityConfigFiles.oidcConfig.oidcClientSecret }}
            jwt_header: "Authorization"
        authentication_backend:
          type: "noop"