# Default values for opensearch-init-ssl.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

kubernetesRole:
  create: true
  kind: Role  # or ClusterRole
  name: opensearch-certificate-manager

job:
  enabled: true
  image: alpine
  repository: mirror.gcr.io
  tag: 3.21.2
  pullPolicy: IfNotPresent
  podAnnotations: {}
  podLabels: {}

caCert:
  country: "FR"
  state: "Ile-de-France"
  location: "Paris"
  organization: "Internal Opensearch"

proxy:
  enable: false
  http_proxy: http://127.0.0.1:8080
  https_proxy: http://127.0.0.1:8080
  ftp_proxy: http://127.0.0.1:8080
  no_proxy: localhost,127.0.0.1,10.0.0.0/8,172.0.0.0/8