{{ if or .Values.scripts.updateSecurityConfig.execute .Values.scripts.createIndice.execute }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name | quote }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    meta.helm.sh/release-name: {{ .Chart.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 3
  template:
    metadata:
      annotations:
        {{- with .Values.job.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- with .Values.job.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      restartPolicy: Never
      containers:
      - name: {{ .Release.Name | quote }}
        image: "{{ .Values.job.repository }}/{{ .Values.job.image }}:{{ .Values.job.tag }}"
        imagePullPolicy: {{ .Values.job.pullPolicy }}
        stdin: true
        stdinOnce: true
        command:
          - /bin/bash
          - -c
        args:
          - |
        {{- if .Values.scripts.updateSecurityConfig.execute }}
            /usr/local/bin/update-security-config.sh
        {{- end }}
        {{- if .Values.scripts.createIndice.execute }}
            /usr/local/bin/create-indice.sh
        {{- end }}
        volumeMounts:
          - name: usr-local-bin-dir
            mountPath: /usr/local/bin/
          - name: opensearch-certificates
            mountPath: /usr/share/opensearch/config/certs
          - name: opensearch-security-config
            mountPath: /usr/share/opensearch/config/opensearch-security/config.yml
            subPath: config.yml
          - name: opensearch-security-internal-users
            mountPath: /usr/share/opensearch/config/opensearch-security/internal_users.yml
            subPath: internal_users.yml
          - name: opensearch-security-roles
            mountPath: /usr/share/opensearch/config/opensearch-security/roles.yml
            subPath: roles.yml
          - name: opensearch-security-roles-mapping
            mountPath: /usr/share/opensearch/config/opensearch-security/roles_mapping.yml
            subPath: roles_mapping.yml
        resources:
          limits:
            memory: 512Mi
            cpu: 2
          requests:
            memory: 256Mi
            cpu: 1
      volumes:
        - name: usr-local-bin-dir
          secret:
            secretName: {{ .Release.Name }}-scripts
            defaultMode: 0755
        - name: opensearch-certificates
          secret:
            secretName: opensearch-certificates
        - name: opensearch-security-config
          secret:
            secretName: opensearch-security-config
        - name: opensearch-security-internal-users
          secret:
            secretName: opensearch-security-internal-users
        - name: opensearch-security-roles
          secret:
            secretName: opensearch-security-roles
        - name: opensearch-security-roles-mapping
          secret:
            secretName: opensearch-security-roles-mapping
{{- end }}