{{- define "common-library.configmap-backend" }}

{{- if .app.configuration_type.backend }}
{{- $configFileName := default "configuration.yaml" .app.configurationFileName }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .app.applicationName }}-back"
  namespace: {{ .root.Release.Namespace }}
data:
  {{ $configFileName }}: |
{{- $configuration := deepCopy .app.configuration }}
{{- $platformAccess := .root.Values.global.platformAccess }}
{{- if and $platformAccess.enabled .root.Values.global.whitelist.enabled }}
{{- fail "global.platformAccess and global.whitelist cannot both be enabled" }}
{{- end }}
{{- if $configuration.security }}
{{- $_ := set $configuration.security "platform_access" (deepCopy $platformAccess) }}
{{- end }}
{{ $configuration | toYaml | indent 4 }}

{{- end }}

{{ end -}}
