{{- define "common-library.configmap-backend" }}

{{- if .app.configuration_type.backend }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .app.applicationName }}-back"
  namespace: {{ .root.Release.Namespace }}
data:
  configuration.yaml: |
{{ .app.configuration | toYaml | indent 4 }}

  .env: |
    {{- range $key, $value := .app.dotenv }}
    {{- if $value }}
    {{ $key }}="{{ $value }}"
    {{- else }}
    {{ $key }}=""
    {{- end }}
    {{- end }}

{{- end }}

{{ end -}}
