{{- define "common-library.configmap-kube" -}}
{{- if and .app.kubeconfig.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .app.applicationName }}-kube"
  namespace: {{ .root.Release.Namespace }}
  labels:
    app: {{ .app.applicationName }} 
  {{- with .app.kubeconfig.annotations }}
  annotations:
{{ toYaml . | nindent 4 }}
  {{- end }}
data:
  kubeconfig: |
{{ toYaml .root.Values.global.kubeconfig | indent 4 }}

{{- end }}
{{end -}}
