{{- define "common-library.configmap-frontend" -}}

{{- if and .app.configuration_type.frontend (or (eq .app.configuration_type.frontend true) (eq .app.configuration_type.frontend.enabled true)) }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .app.applicationName }}-front"
data:
  config.json: |
{{ .app.configuration.config_json | toJson | nindent 4 }}

{{- end }}

{{ end -}}
