{{- define "common-library.serviceaccount" -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .app.applicationName }}
  namespace: {{ .root.Release.Namespace }}
{{- with .app.serviceAccount.labels }}
  labels:
{{- toYaml . | nindent 4 }}
{{- end }}
{{- with .app.serviceAccount.annotations }}
  annotations:
{{- toYaml . | nindent 4 }}
{{- end }}
automountServiceAccountToken: {{ .app.serviceAccount.automountServiceAccountToken }}

{{ end -}}