"""add platform_announcement table

Revision ID: b88202b8451e
Revises: a3f7c9e2d514
Create Date: 2026-09-25 16:31:57.265609

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
# codeql[py/unused-global-variable]
revision: str = "b88202b8451e"
# codeql[py/unused-global-variable]
down_revision: Union[str, Sequence[str], None] = "a3f7c9e2d514"
# codeql[py/unused-global-variable]
branch_labels: Union[str, Sequence[str], None] = None
# codeql[py/unused-global-variable]
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "platform_announcement",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "severity",
            sa.String(length=16),
            nullable=False,
            comment="Banner severity: info | warning | error | success. Fixes both the colour and the icon; neither is separately authorable.",
        ),
        sa.Column(
            "title",
            sa.JSON(),
            nullable=False,
            comment="Locale → title map (e.g. {'en': ..., 'fr': ...}), resolved against the viewer's locale with an 'en' fallback.",
        ),
        sa.Column(
            "description_short",
            sa.JSON(),
            nullable=False,
            comment="Locale → markdown map shown in the banner itself.",
        ),
        sa.Column(
            "description_long",
            sa.JSON(),
            nullable=False,
            comment="Locale → markdown map shown in the more-info dialog. Empty for every locale means the banner offers no more-info action.",
        ),
        sa.Column("enabled", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("dismissible", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "content_version",
            sa.Integer(),
            server_default="1",
            nullable=False,
            comment="Bumped only when reader-visible content changes, never on an enabled/disabled toggle. Keys the frontend's per-browser dismissal.",
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_platform_announcement_enabled",
        "platform_announcement",
        ["enabled"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_platform_announcement_enabled", table_name="platform_announcement"
    )
    op.drop_table("platform_announcement")
    # ### end Alembic commands ###
