---
apiVersion: v1
kind: ConfigMap
metadata:
  name: opensearch-certificate-script
data:
  opensearch-gen-certificates.sh: |
{{ tpl (.Files.Get "scripts/opensearch-gen-certificates.sh") . | indent 4 }}
{{ if .Values.proxy.enable }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-env
data:
  HTTP_PROXY: {{ .Values.proxy.http_proxy }}
  HTTPS_PROXY: {{ .Values.proxy.https_proxy }}
  FTP_PROXY: {{ .Values.proxy.ftp_proxy }}
  NO_PROXY: {{ .Values.proxy.no_proxy }}
{{- end }}