{{ if .Values.kubernetesRole.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ .Values.kubernetesRole.kind }}
metadata:
  name: {{ .Values.kubernetesRole.name }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - create
  - patch
{{- end }}