"""update_data_session_add_team_id_in_json

Revision ID: 82d43cf766d9
Revises: e89ab9e7ca5f
Create Date: 2026-04-10 08:13:59.051649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82d43cf766d9'
down_revision: Union[str, Sequence[str], None] = 'e89ab9e7ca5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("""
        UPDATE session
        SET session_data = session_data || jsonb_build_object('team_id', team_id)
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
