services:

# -----------------------------------------------------------------------------
# FRED dev container
# -----------------------------------------------------------------------------

  devcontainer:
    image: fred/devcontainer:0.1
    container_name: fred-devcontainer
    hostname: fred-devcontainer
    build:
      context: ../..
      dockerfile: .devcontainer/Dockerfile-devcontainer
    env_file: "~/.fred/openai-api-key.env"
    tty: true
    command:
      - /bin/bash
    volumes:
      - ../..:/app
      - /app/frontend/node_modules
      - /app/backend/.venv
      - /app/backend/target
      - vol-kubeconfig:/home/fred-user/.kube:ro
    networks:
      - fred-network
    ports:
      - "0.0.0.0:8000:8000/tcp"
      - "0.0.0.0:5173:5173/tcp"
    depends_on:
      postgres:
        condition: service_healthy
      opensearch-dashboards:
        condition: service_healthy
      minio-post-install-job:
        condition: service_completed_successfully
      kube-post-install-job:
        condition: service_completed_successfully
