_meta:
  type: "internalusers"
  config_version: 2

admin:
  hash: $2y$12$h.SKV7oNwGH1YzXR4kuNj.h.JadXGymBLGnAbxnlcYoCZ5BLwE7em

fred_rw:
  hash: $2y$12$h.SKV7oNwGH1YzXR4kuNj.h.JadXGymBLGnAbxnlcYoCZ5BLwE7em

fred_ro:
  hash: $2y$12$h.SKV7oNwGH1YzXR4kuNj.h.JadXGymBLGnAbxnlcYoCZ5BLwE7em
