PROJECT_NAME=fred-capability-platform-ops
PY_PACKAGE=fred_capability_platform_ops

include ../../scripts/makefiles/python-vars.mk

include ../../scripts/makefiles/python-deps.mk
include ../../scripts/makefiles/python-code-quality.mk
include ../../scripts/makefiles/python-test.mk
include ../../scripts/makefiles/python-clean.mk
include ../../scripts/makefiles/python-publish.mk
include ../../scripts/makefiles/help.mk
