VERSION=0.1.0
PROJECT_NAME=fred-core
PY_PACKAGE=fred_core

include ../scripts/makefiles/python-vars.mk

include ../scripts/makefiles/python-deps.mk
include ../scripts/makefiles/python-code-quality.mk
include ../scripts/makefiles/python-clean.mk
include ../scripts/makefiles/help.mk