PROJECT_NAME=fred-capability-team-wiki
PY_PACKAGE=fred_capability_team_wiki

include ../../scripts/makefiles/python-vars.mk

include ../../scripts/makefiles/python-deps.mk
include ../../scripts/makefiles/python-code-quality.mk
include ../../scripts/makefiles/python-test.mk
include ../../scripts/makefiles/python-clean.mk
include ../../scripts/makefiles/python-publish.mk
include ../../scripts/makefiles/help.mk
