{{ if or .Values.scripts.updateSecurityConfig.execute .Values.scripts.createIndice.execute }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-scripts
type: Opaque
stringData:
{{- if .Values.scripts.updateSecurityConfig.execute }}
  update-security-config.sh: |
{{ tpl (.Files.Get "scripts/update-security-config.sh") . | indent 4 }}
{{- end }}
{{- if .Values.scripts.createIndice.execute }}
  create-indice.sh: |
{{ tpl (.Files.Get "scripts/create-indice.sh") . | indent 4 }}
{{- end }}
{{- end }}