dotenv:
  AZURE_TENANT_ID: "${AZURE_TENANT_ID}"
  AZURE_CLIENT_ID: "${AZURE_CLIENT_ID}"
  AZURE_CLIENT_SECRET: "${AZURE_CLIENT_SECRET}"
  AZURE_CLIENT_SCOPE: "${AZURE_CLIENT_SCOPE}"

  AZURE_API_VERSION: "${AZURE_API_VERSION}"

  AZURE_APIM_BASE_URL: "${AZURE_APIM_BASE_URL}"
  AZURE_RESOURCE_PATH_EMBEDDINGS: "${AZURE_RESOURCE_PATH_EMBEDDINGS}"
  AZURE_RESOURCE_PATH_LLM: "${AZURE_RESOURCE_PATH_LLM}"
  AZURE_APIM_KEY: "${AZURE_APIM_KEY}"

  AZURE_OPENAI_BASE_URL: "${AZURE_OPENAI_BASE_URL}"
  AZURE_OPENAI_API_KEY: "${AZURE_OPENAI_API_KEY}"

  AZURE_DEPLOYMENT_LLM: "${AZURE_DEPLOYMENT_LLM}"
  AZURE_DEPLOYMENT_EMBEDDING: "${AZURE_DEPLOYMENT_EMBEDDING}"

  OPENAI_API_KEY: "${OPENAI_API_KEY}"
  OPENAI_API_VERSION: "${OPENAI_API_VERSION}"

  OLLAMA_API_URL: "${OLLAMA_API_URL}"
  OLLAMA_EMBEDDING_MODEL_NAME: "${OLLAMA_EMBEDDING_MODEL_NAME}"
  OLLAMA_VISION_MODEL_NAME: "${OLLAMA_VISION_MODEL_NAME}"

  KEYCLOAK_SERVER_URL: "${KEYCLOAK_SERVER_URL}"
  KEYCLOAK_REALM_NAME: "${KEYCLOAK_REALM_NAME}"
  KEYCLOAK_CLIENT_ID: "${KEYCLOAK_CLIENT_ID}"

  OPENSEARCH_USER: "${OPENSEARCH_USER}"
  OPENSEARCH_PASSWORD: "${OPENSEARCH_PASSWORD}"

  MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY}"
  MINIO_SECRET_KEY: "${MINIO_SECRET_KEY}"

  GCS_CREDENTIALS_PATH: "${GCS_CREDENTIALS_PATH}"
  GCS_BUCKET_NAME: "${GCS_BUCKET_NAME}"
  GCS_PROJECT_ID: "${GCS_PROJECT_ID}"
