services:
     
# -----------------------------------------------------------------------------
# Fred frontend and backend
# -----------------------------------------------------------------------------

  agentic-backend:
    image: registry.thalesdigital.io/tsn/innovation/projects/fred/agentic-backend:0.1
    container_name: agentic-backend
    build:
      context: ../../agentic_backend
      dockerfile: dockerfiles/Dockerfile-dev
    env_file: "~/.fred/openai-api-key.env"
    environment:
      NO_PROXY: "*"
      PYTHONUNBUFFERED: 1  # Pour voir les logs en temps réel
    command:
      - --server.configurationPath
      - /app/config/configuration.yaml
      - --server.baseUrlPath
      - /fred
    volumes:
      - ../../agentic_backend:/app
      - vol-kubeconfig:/home/fred-user/.kube:ro
    networks:
      - app-network
    ports:
      - "0.0.0.0:8000:8000/tcp"
      - "5678:5678"  # Port pour le débogueur


  frontend:
    image: registry.thalesdigital.io/tsn/innovation/projects/fred/frontend:0.1
    container_name: fred-frontend
    build:
      context: ../../frontend
      dockerfile: dockerfiles/Dockerfile-dev
    environment:
      NO_PROXY: "*"
      VITE_BACKEND_URL_API: http://localhost:8000
      VITE_WEBSOCKET_URL: ws://localhost:8000/fred/chatbot/query
      VITE_USE_AUTH: false
    volumes:
      - ../../frontend:/app
    networks:
      - app-network
    ports:
      - "0.0.0.0:5173:5173/tcp"

  knowledge-flow-backend:
    image: registry.thalesdigital.io/tsn/projects/knowledge_flow_app/knowledge-flow-backend:0.1
    container_name: knowledge-flow-backend
    build:
      context: ../../knowledge_flow_backend
      dockerfile: dockerfiles/Dockerfile-dev
    environment:
      NO_PROXY: "*"
    command:
      - --config-path 
      - /app/config/configuration.yaml
    volumes:
      # Mount the whole project (RW mode)
      - ../../knowledge_flow_backend:/app:rw
    networks:
      - app-network
    ports:
      - "0.0.0.0:8111:8111/tcp"

volumes:
  vol-kubeconfig:
    external: true
    name: vol-kubeconfig

networks:
  app-network:
    external: true
    name: fred-shared-network