# spe frontend

imagePullSecretName: []
ingress:
  enabled: true
  className: "traefik"
  annotations: {}
  hosts:
    - host: fred.dev.fred.thalesgroup.com
      paths:
        - path: /
  tls:
    - secretName: fred-frontend-crt
      hosts:
        - fred.dev.fred.thalesgroup.com

config:
  backendUrlApi: "http://fred-backend.dev.fred.thalesgroup.com"
  backendUrlKnowledge: "http://knowledge-flow-backend.dev.fred.thalesgroup.com"
  websocketUrl: "ws://fred-backend.dev.fred.thalesgroup.com/fred/chatbot/query"

env:
  - name: VITE_ALLOWED_HOSTS
    value: "fred.dev.fred.thalesgroup.com"
  - name: VITE_BACKEND_URL_KNOWLEDGE
    value: "http://knowledge-flow-backend.dev.fred.thalesgroup.com"
  - name: VITE_USE_AUTH
    value: "true"

oidc:
  config:
    authServerUrl: "https://idp.dev.fred.thalesgroup.com/"