apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.applicationName }}-configmap"
  namespace: {{ .Release.Namespace }}
data:
  configuration.yaml: |

    app:
      name: "{{ .Values.applicationName }}"
      version: "{{ .Values.image.tag }}"
      debug: false

{{ .Values.configuration | toYaml | indent 4 }}

  .env: |
    {{- range $key, $value := .Values.dotenv }}
    {{- if $value }}
    {{ $key }}="{{ tpl $value $ }}"
    {{- else }}
    {{ $key }}=""
    {{- end }}
    {{- end }}
