apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Chart.Name }}-kubeconfig"
  namespace: {{ .Release.Namespace }}
  {{- if .Values.kubeconfig.annotations }}
  annotations:
{{ toYaml .Values.kubeconfig.annotations | indent 4 }}
  {{- end }}
  labels:
    name: {{ .Release.Name }}
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: "{{ .Values.applicationName }}"
    heritage: "{{ .Release.Service }}"
    {{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels.data | indent 4 }}
    {{- end }}
type: Opaque
data:
{{- range $key, $value := .Values.kubeconfig.data }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}